services:
  postgres:
    image: postgis/postgis:15-3.3-alpine
    container_name: nest-admin-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: nest-admin-soybean
    ports:
      - "5432:5432"
    volumes:
      - ./db/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d nest-admin-soybean"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: nest-admin-redis
    command: redis-server --requirepass 123456
    ports:
      - "6379:6379"
    volumes:
      - ./db/redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "123456", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
